name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print environmental variables
        run: printenv
      - name: Print full GitHub context
        run: echo '${{ toJson(github) }}'      
      - name: Print full GitHub context
        run: echo '${{ github }}'
